debug: false
realipheader: ""
language: zh_CN
sitename: Nezha Monitor
usertemplate: user-dist
admintemplate: admin-dist
jwtsecretkey: -jwt-secret-key-
agentsecretkey: -agent-secret-key-
listenport: 8080
listenhost: "0.0.0.0"
installhost: "-install-host-"
tls: false
location: Asia/Shanghai
forceauth: false
enableplainipinnotification: false
enableipchangenotification: false
ipchangenotificationgroupid: 0
cover: 1
ignoredipnotification: ""
ignoredipnotificationserverids: {}
avgpingcount: 2
dnsservers: ""
customcode: ""
customcodedashboard: ""
oauth2: {}